[book]
title = "Rael III"
authors = ["Rael"]
description = "Web book of Rael's third publication."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/wheelofheaven/rael-one-the-book-which-tells-the-truth"
git-repository-icon = "fa-github"
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
